#!/usr/bin/with-contenv bash

# make our folders
mkdir -p /config/{nginx/site-confs,log/nginx,keys} 

# copy config files
[[ ! -f /config/nginx/nginx.conf ]] && \
    cp /defaults/nginx.conf /config/nginx/nginx.conf
[[ ! -f /config/nginx/site-confs/default ]] && \
    cp /defaults/default /config/nginx/site-confs/default

# permissions
chown -R abc:abc /config 
chmod -R g+w /config/nginx
chmod -R 644 /etc/logrotate.d